// AI 配置常量
export const AI_SERVICES = [
  {
    value: 'builtin',
    label: '内置服务（免费）',
    endpoint: 'https://proxy-ai.doocs.org/v1',
    needsApiKey: false,
    models: [
      'Qwen/Qwen2.5-7B-Instruct',
      'Qwen/Qwen2.5-Coder-7B-Instruct',
      'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
      'THUDM/GLM-Z1-9B-0414',
      'internlm/internlm2_5-7b-chat',
      'qwen/qwen3-30b-a3b:free',
      'qwen/qwen3-235b-a22b:free',
      'thudm/glm-z1-32b:free',
      'deepseek/deepseek-v3-base:free',
    ],
  },
  {
    value: 'deepseek',
    label: 'DeepSeek',
    endpoint: 'https://api.deepseek.com/v1',
    needsApiKey: true,
    models: ['deepseek-chat', 'deepseek-reasoner', 'deepseek-coder'],
  },
  {
    value: 'openai',
    label: 'OpenAI',
    endpoint: 'https://api.openai.com/v1',
    needsApiKey: true,
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo', 'o1', 'o1-mini'],
  },
  {
    value: 'qwen',
    label: '通义千问',
    endpoint: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    needsApiKey: true,
    models: [
      'qwen-max',
      'qwen-plus',
      'qwen-turbo',
      'qwen-long',
      'qwen2.5-72b-instruct',
      'qwen2.5-32b-instruct',
      'qwen2.5-14b-instruct',
      'qwen2.5-7b-instruct',
      'qwen2.5-coder-32b-instruct',
    ],
  },
  {
    value: 'hunyuan',
    label: '腾讯混元',
    endpoint: 'https://api.hunyuan.cloud.tencent.com/v1',
    needsApiKey: true,
    models: ['hunyuan-pro', 'hunyuan-standard', 'hunyuan-lite', 'hunyuan-turbo'],
  },
  {
    value: 'doubao',
    label: '火山方舟（豆包）',
    endpoint: 'https://ark.cn-beijing.volces.com/api/v3',
    needsApiKey: true,
    modelHint: 'model 需填写推理接入点 ID（ep-xxxx），在火山方舟控制台创建接入点后获取',
    models: ['ep-xxxxxxxx', 'doubao-pro-32k', 'doubao-pro-4k', 'doubao-lite-32k', 'doubao-lite-4k'],
  },
  {
    value: 'doubao-ai',
    label: '豆包 AI',
    endpoint: 'https://api.doubao-ai.com/v1',
    needsApiKey: true,
    models: ['doubao-pro-v1'],
  },
  {
    value: 'siliconflow',
    label: '硅基流动',
    endpoint: 'https://api.siliconflow.cn/v1',
    needsApiKey: true,
    models: [
      'Qwen/Qwen2.5-7B-Instruct',
      'Qwen/Qwen2.5-Coder-7B-Instruct',
      'deepseek-ai/DeepSeek-V3',
      'deepseek-ai/DeepSeek-R1',
      'THUDM/glm-4-9b-chat',
      'meta-llama/Llama-3.3-70B-Instruct',
    ],
  },
  {
    value: '302ai',
    label: '302.AI',
    endpoint: 'https://api.302.ai/v1',
    needsApiKey: true,
    models: [
      'gpt-4o',
      'gpt-4o-mini',
      'claude-3-5-sonnet-20241022',
      'gemini-2.0-flash-exp',
      'deepseek-chat',
      'qwen-max',
    ],
  },
  {
    value: 'zhipu',
    label: '智谱 AI',
    endpoint: 'https://open.bigmodel.cn/api/paas/v4',
    needsApiKey: true,
    models: ['glm-4-plus', 'glm-4-0520', 'glm-4-air', 'glm-4-airx', 'glm-4-flash'],
  },
  {
    value: 'baichuan',
    label: '百川智能',
    endpoint: 'https://api.baichuan-ai.com/v1',
    needsApiKey: true,
    models: ['Baichuan4', 'Baichuan3-Turbo', 'Baichuan3-Turbo-128k', 'Baichuan2-Turbo'],
  },
  {
    value: 'yi',
    label: '零一万物',
    endpoint: 'https://api.lingyiwanwu.com/v1',
    needsApiKey: true,
    models: ['yi-lightning', 'yi-large', 'yi-medium', 'yi-spark', 'yi-large-turbo'],
  },
  {
    value: 'moonshot',
    label: '月之暗面（Kimi）',
    endpoint: 'https://api.moonshot.cn/v1',
    needsApiKey: true,
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
  },
  {
    value: 'qianfan',
    label: '百度千帆',
    endpoint: 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop',
    needsApiKey: true,
    models: ['ernie-4.0-8k', 'ernie-3.5-8k', 'ernie-speed-128k', 'ernie-lite-8k', 'ernie-tiny-8k'],
  },
  {
    value: 'custom',
    label: '自定义（兼容 OpenAI API）',
    endpoint: '',
    needsApiKey: true,
    models: ['gpt-3.5-turbo', 'gpt-4'],
  },
]

export const DEFAULT_CONFIG = {
  type: 'builtin',
  endpoint: 'https://proxy-ai.doocs.org/v1',
  apiKey: '',
  model: 'Qwen/Qwen2.5-7B-Instruct',
  temperature: 0.6,
  maxTokens: 1536,
  customModels: {}, // 各服务商自定义模型 { [serviceType]: string[] }
}

export const DEFAULT_QUICK_COMMANDS = [
  {
    id: 'polish',
    label: '润色',
    icon: 'Sparkles',
    template: '请润色以下内容，使其更加流畅、专业：\n\n{{sel}}',
  },
  {
    id: 'translate-en',
    label: '翻译成英文',
    icon: 'Languages',
    template: '请将以下内容翻译为英文：\n\n{{sel}}',
  },
  {
    id: 'translate-zh',
    label: '翻译成中文',
    icon: 'Languages',
    template: 'Please translate the following content into Chinese:\n\n{{sel}}',
  },
  {
    id: 'summary',
    label: '总结',
    icon: 'FileText',
    template: '请对以下内容进行总结，提取核心要点：\n\n{{sel}}',
  },
  {
    id: 'expand',
    label: '扩写',
    icon: 'Maximize2',
    template: '请扩写以下内容，增加更多细节和说明：\n\n{{sel}}',
  },
  {
    id: 'rewrite',
    label: '改写',
    icon: 'RefreshCw',
    template: '请改写以下内容，保持原意但使用不同的表达方式：\n\n{{sel}}',
  },
]
